const state = {
  image: null,
  params: null,
  metrics: null,
  running: false,
  startPending: false,
  trainingGeneration: 0,
  trainingRun: null,
  sampleLoading: false,
  imageLoading: false,
  paused: false,
  stopRequested: false,
  trainingTiming: {
    elapsedMs: 0,
    iterationsPerSecond: 0,
    sampleElapsedMs: 0,
    sampleSteps: 0,
    lastStep: 0,
  },
  webgpu: { supported: false, renderer: null, reason: "checking", limits: null, adapterInfo: null },
  recommendation: null,
  safety: {
    mode: "on",
    memoryLimiterUnlocked: false,
    lastStopReason: "",
    lastStopEstimateMB: "",
    lastStopBudgetMB: "",
    lastRecommended: "",
  },
  lastDownload: "",
  lastGpuLoss: null,
  lastInputMode: "",
  imageLoadGeneration: 0,
  exportReady: false,
  exporting: false,
  adjustingSplats: false,
  splatBaseline: null,
  splatAdjustmentVersion: 0,
  splatAdjustmentFrame: 0,
  splatAdjustmentValidationTimer: 0,
  splatAdjustmentProcessing: false,
  splatAdjustmentRenderedVersion: 0,
  splatAdjustmentValidationVersion: 0,
  splatAdjustmentEpoch: 0,
  splatInspectorNonfiniteCache: null,
  splatAdjustmentStats: { requests: 0, renders: 0, staleDropped: 0, yields: 0, lastMs: 0 },
  splatPreviewShape: "gaussian",
  runtimeSettingsRevision: 0,
  previewGeneration: 0,
  previewRequestedRevision: 0,
  previewAppliedRevision: 0,
  previewAppliedAlphaBackground: "",
  previewRefreshPending: false,
  previewRefreshPromise: Promise.resolve(false),
  previewRefreshEpoch: 0,
  webGpuRecoveryGeneration: 0,
  webGpuRecoveryPending: false,
  webGpuRecoveryAttempts: 0,
  previewMode: "original",
  previewPadding: { x: 0, y: 0, width: 0, height: 0, bytes: 0 },
  gpuMemory: {
    activeBytes: 0,
    reservedBytes: 0,
    trainingActiveBytes: 0,
    trainingReservedBytes: 0,
    resultActiveBytes: 0,
    resultReservedBytes: 0,
  },
  capacityProbe: { status: "manual", requested: 0, selected: 0, attempts: [], fastPath: true },
  canvasView: { mode: "fit", scale: 1, panX: 0, panY: 0, pointerId: null, lastX: 0, lastY: 0 },
  canvasPointers: new Map(),
  canvasPinch: null,
  visibilityPaused: false,
  layerTelemetryState: null,
  // Virtual-camera sampling is default-off. A sparse map avoids reserving one
  // empty string per requested iteration for the rare enabled runs.
  virtualCameraByStep: new Map(),
  tilt: {
    controller: null,
    abortController: null,
    revision: "",
    loading: false,
    generation: 0,
    plyDigest: "",
    plyByteLength: 0,
    vertices: 0,
    verifiedRevision: "",
    verifiedPlyDigest: "",
    verifiedPlyByteLength: 0,
    teacherViewsLoading: false,
    teacherViews: [],
    teacherFrameRequest: 0,
    viewMode: "splats",
    cameraMarkersVisible: true,
    radiusMode: "training",
  },
  exportMessage: "Finish training before export.",
};
